name: "deploy-action"
description: "Deploy to Kubernetes"
author: "Pedro Gutiérrez"
branding:
  icon: "cloud"
  color: "blue"
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  docker_tag:
    description: "The docker tag to publish"
  docker_password:
    description: "Docker password"
  kubeconfig:
    description: "Base64 encoded json with a kubeconfig"
  secrets_name:
    description: "A name for the Kubernetes secrets to create"
  secrets:
    description: "Base64 encoded json with secrets"
  kill:
    description: "A selector for pods to be killed"
